spring:
  datasource:
    url: jdbc:h2:file:./data/momentumDB
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 15

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      temperature: 0.7
      model: gpt-4o

  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 8080

logging:
    level:
        org.springframework: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: DEBUG