spring:
  datasource:
    url: jdbc:h2:file:./data/momentumDB
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console


openai:
  api:
    key: ${OPENAI_API_KEY:}
    base-url: https://api.openai.com/v1
    model: gpt-4o
    temperature: 0.7
    chat-completions-uri: /chat/completions


server:
  port: 8081

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: INFO