spring.data.mongodb:
  uri: mongodb://localhost:27017
  database: mini-momentum

openai:
  api:
    key: ${OPENAI_API_KEY}
    base-url: https://api.openai.com/v1
    model: gpt-4o
    temperature: 0.7
    chat-completions-uri: /chat/completions


server:
  port: 8081

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: INFO